services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    command: --local-infile=1
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpwd 
      MYSQL_DATABASE: mydatabase # Optional: creates a database on startup
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Persist data to a named volume
      # Put your own directory-to-container-directory mappings here

volumes:
  mysql_data: # Defines the named volume
